name: Staging deployment

on:
  push:
    branches: [ develop ]
    
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '17.x'
      
      - name: Notify
        uses: jasongitmail/fast-webhook@v1.1.4
        with:
          url: https://api.pushover.net/1/messages.json
          json: |
            {
              "token": "${{ secrets.PUSHOVER_TOKEN }}",
              "user": "${{ secrets.PUSHOVER_USER }}",
              "message": "Démarrage du build pour 'dev.re-unir.fr'."
            }

      - name: Install dependancies
        env:
          NODE_OPTIONS: --openssl-legacy-provider
        run: yarn install
        
      - name: Configure robots.txt
        run: |
          cp public/robots-dev.txt public/robots.txt
          rm public/robots-prod.txt public/robots-dev.txt
          
      - name: Build
        env:
          NODE_OPTIONS: --openssl-legacy-provider
        run: yarn build
          
      - name: Notify
        uses: jasongitmail/fast-webhook@v1.1.4
        with:
          url: https://api.pushover.net/1/messages.json
          json: |
            {
              "token": "${{ secrets.PUSHOVER_TOKEN }}",
              "user": "${{ secrets.PUSHOVER_USER }}",
              "message": "Mise en production de 'dev.re-unir.fr'."
            }
          
      - name: Deploy to Infomaniak
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: '464i8_ci'
          server: '464i8.ftp.infomaniak.com'
          ssh_private_key: ${{ secrets.SSH_KEY }} 
          local_path: './build/*'
          remote_path: './sites/clients/reunir/dev'
          
      - name: Notify
        uses: jasongitmail/fast-webhook@v1.1.4
        with:
          url: https://api.pushover.net/1/messages.json
          json: |
            {
              "token": "${{ secrets.PUSHOVER_TOKEN }}",
              "user": "${{ secrets.PUSHOVER_USER }}",
              "message": "L'application (dev) 'dev.re-unir.fr' a bien été déployée sur l'infrastructure Infomaniak."
            }
