name: Deploy in Prod Env

on:
  push:
    branches: [ main ]
    
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '17.x'
      
      - name: notify
        uses: jasongitmail/fast-webhook@v1.1.4
        with:
          url: https://api.pushover.net/1/messages.json
          json: |
            {
              "token": "${{ secrets.PUSHOVER_TOKEN }}",
              "user": "${{ secrets.PUSHOVER_USER }}",
              "message": "Démarrage du build pour 'ré-unir.fr'."
            }

      - name: install
        env:
          NODE_OPTIONS: --openssl-legacy-provider
        run: yarn install
        
      - name: configure
        run: |
          cp public/robots-prod.txt public/robots.txt
          rm public/robots-prod.txt public/robots-dev.txt
          
      - name: build
        env:
          NODE_OPTIONS: --openssl-legacy-provider
        run: yarn build
          
      - name: notify
        uses: jasongitmail/fast-webhook@v1.1.4
        with:
          url: https://api.pushover.net/1/messages.json
          json: |
            {
              "token": "${{ secrets.PUSHOVER_TOKEN }}",
              "user": "${{ secrets.PUSHOVER_USER }}",
              "message": "Mise en production de 're-unir.fr'."
            }
          
      - name: deploy
        uses: wangyucode/sftp-upload-action@v1.1
        with:
          host: 464i8.ftp.infomaniak.com
          port: 22
          username: 464i8_ci
          password: ${{ secrets.SFTP_PASS }}
          localDir: ./build/
          remoteDir: ~/sites/clients/reunir/prod
          
      - name: notify
        uses: jasongitmail/fast-webhook@v1.1.4
        with:
          url: https://api.pushover.net/1/messages.json
          json: |
            {
              "token": "${{ secrets.PUSHOVER_TOKEN }}",
              "user": "${{ secrets.PUSHOVER_USER }}",
              "message": "L'application 'ré-unir.fr' a bien été déployée sur l'infrastructure Infomaniak."
            }
