name: Production deployment

on:
  push:
    branches: [ main ]
    
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '17.x'
      
      - name: Notify
        uses: jasongitmail/fast-webhook@v1.1.4
        with:
          url: https://api.pushover.net/1/messages.json
          json: |
            {
              "token": "${{ secrets.PUSHOVER_TOKEN }}",
              "user": "${{ secrets.PUSHOVER_USER }}",
              "message": "Démarrage du build pour 'ré-unir.fr'."
            }

      - name: Install dependancies
        env:
          NODE_OPTIONS: --openssl-legacy-provider
        run: yarn install
        
      - name: Configure robots.txt
        run: |
          cp public/robots-prod.txt public/robots.txt
          rm public/robots-prod.txt public/robots-dev.txt
          
      - name: Build
        env:
          NODE_OPTIONS: --openssl-legacy-provider
        run: yarn build
          
      - name: Notify
        uses: jasongitmail/fast-webhook@v1.1.4
        with:
          url: https://api.pushover.net/1/messages.json
          json: |
            {
              "token": "${{ secrets.PUSHOVER_TOKEN }}",
              "user": "${{ secrets.PUSHOVER_USER }}",
              "message": "Mise en production de 'ré-unir.fr'."
            }
          
      - name: Deploy to Infomaniak
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "build/"
          REMOTE_HOST: 464i8.ftp.infomaniak.com
          REMOTE_USER: 464i8_ci
          TARGET: /home/clients/04cd6fa9bfb5342793851e99c0041e14/sites/clients/reunir/prod

      - name: Notify on success
        uses: jasongitmail/fast-webhook@v1.1.4
        with:
          url: https://api.pushover.net/1/messages.json
          json: |
            {
              "token": "${{ secrets.PUSHOVER_TOKEN }}",
              "user": "${{ secrets.PUSHOVER_USER }}",
              "message": "L'application 'ré-unir.fr' a bien été déployée sur l'infrastructure Infomaniak."
            }

      - name: Notify on failure
        if: ${{ failure() }}
        uses: jasongitmail/fast-webhook@v1.1.4
        with:
          url: https://api.pushover.net/1/messages.json
          json: |
            {
              "token": "${{ secrets.PUSHOVER_TOKEN }}",
              "user": "${{ secrets.PUSHOVER_USER }}",
              "message": "Erreur lors du déploiement de 'ré-unir.fr' sur l'infrastructure Infomaniak."
            }