name: Build test

on:
  push:
    branches: [ develop ]
    
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '17.x'

      - name: Install dependancies
        env:
          NODE_OPTIONS: --openssl-legacy-provider
        run: yarn install
          
      - name: Build
        env:
          NODE_OPTIONS: --openssl-legacy-provider
        run: yarn build
          